### PR TITLE
fixes #50 - replaced deprecated yum localinstall by rpm command

### LINKED ISSUE #50: get_bootstrap_rpm doesn't die in case if remote package doesn't exist
`get_bootstrap_rpm` calls `exec_failexit` on `yum localinstall` but due to way `yum` handles responses, it does not catch the failure in download of the package:

``` bash
> yum -y localinstall http://completely.fictive.hostname/foo.rpm --nogpgcheck
Loaded plugins: product-id, security, subscription-manager
Setting up Local Package Process
Cannot open: http://completely.fictive.hostname/foo.rpm. Skipping.
Nothing to do
> echo $?
0
```
- so it evaluates this situation as a success and continues.

### PR DESCRIPTION
**Pull request by rplevka**
Addresses #50 .

### CODE REVIEW

**Comment by evgeni** [comment]
IMHO this should be `rpm -ivh http://%s/pub/katello-ca-consumer-latest.noarch.rpm` to match what we do in kickstart and support RHEL5 which does not have this functionality.

**Comment by evgeni** [comment]
ah, one thing:
drop the path please, it's /bin/rpm on rhel5/6 but /usr/bin/rpm on rhel7 (due to merged /bin:/usr/bin)

**Comment by evgeni** [comment]
:+1:

**Comment by CalvinHartwell** [comment]
> IMHO this should be rpm -ivh http://%s/pub/katello-ca-consumer-latest.noarch.rpm to match what we do in kickstart and support RHEL5 which does not have this functionality.

Should also limit any future issues with DNF? :+1:

**Comment by mccun934** [comment]
needs a rebase

**Comment by rplevka** [comment]
@mccun934 rebased

**Comment by Rocco83** [comment]
@evgeni based on http://www.linuxquestions.org/questions/linux-newbie-8/rpm-uvh-or-ivh-116706/ why should we use ivh instead of uvh?

**Comment by evgeni** [comment]
@Rocco83 mainly to match what we do in Kickstart:
https://github.com/Katello/katello/blob/master/app/views/foreman/unattended/snippets/_subscription_manager_registration.erb

**Comment by Rocco83** [comment]
interesting. my question btw is the same, but apply also to kickstart :)
  rpm -ivh <%= subscription_manager_configuration_url(@host) %>
why -ivh and not -Uvh?

**Comment by rplevka** [comment]
@Rocco83 After browsing some official documentation and knowledge bases I noticed they also use `-Uvh` so I decided to go with your suggestion.
- also fixed few (unrelated) formatting nitpicks my linter has highlighted

**Comment by evgeni** [comment]
:+1:

LGTM, ship it :)

**Comment by evgeni** [comment]
oh, wait! it has sat6_fqdn again, that's foreman_fqdn now!

**Comment by rplevka** [comment]
@evgeni, d'oh...good catch. let me fix that real quick

Done!

**Comment by rplevka** [comment]
@evgeni done

**Comment by evgeni** [comment]
:)
you also probably want to look at the print line for "Retrieving Candlepin Consumer RPMs", I think @mccun934 changed it on purose

**Comment by evgeni** [comment]
good now :)

**Comment by rplevka** [comment]
@evgeni, ok, done - undone that change - can you review once again, pls? :)

**Comment by Rocco83** [comment]
seems good to me as well :)

**Pull request merged**
