### PR TITLE
call rhn-migrate-classic-to-rhsm with --remove-rhn-packages

### PR DESCRIPTION
**Pull request by evgeni**
but only if we have removepkgs set (which is the default, though)

### CODE REVIEW

**Review by sideangleside — COMMENTED** [review]
Not every version of rhn-migrate-classic-to-rhsm supports the --remove-rhn-packages option. see (https://bugzilla.redhat.com/show_bug.cgi?id=1185914) so I'd be a little uncomfortable calling it blindly. 

We could either check for an appropriate version and call it only in that use case or stick with our function that removes packages. The upside of our function is that it works in all uses (migration and registration)

**Comment by evgeni** [comment]
bah, you are right. we'd have to wrap that into if version... bah bah bah

my idea was to keep both, as this allows us to benefit from the knowledge inside of migrate-to-rhsm

**Comment by sideangleside** [comment]
It doesn't hurt to run both. I'm OK with this.

**Comment by evgeni** [comment]
Just so that I don't loose the link: https://bugzilla.redhat.com/show_bug.cgi?id=1185914

**Comment by beav** [comment]
@evgeni this PR needs a rebase

**Review by ehelms — APPROVED** [review]

**Pull request merged**
