### PR TITLE
Added documentation and reshuffled code with __main__ check for pydoc…

### PR DESCRIPTION
**Pull request by ericzolf**
Add documentation and reshuffled code with main check for pydoc usage.
Add comments with double hash (##) to better understand flow of script (that was actually a learning activity for me).
Use pydoc ./bootstrap.py to get the documentation.
Use awk -F## 'NF>1 {print $2}' ./bootstrap.py to see the flow.
The commit is relatively important but if you look at the diff, you'll see that the code actually doesn't change, with the exception of the main check, and that only lines have been moved around and comments / documentation added all over the place.

There are a few TODO marks where I was not sure what the purpose / reason / context of the commented code was supposed to be.

### CODE REVIEW

**Comment by beav** [comment]
@ericzolf  Since you are fixing related items, can you also fix pep8? A first pass with E501 disabled shows:

```
$ pep8 --ignore E501 bootstrap.py
bootstrap.py:98:14: E261 at least two spaces before inline comment
bootstrap.py:99:30: E226 missing whitespace around arithmetic operator
bootstrap.py:99:44: E261 at least two spaces before inline comment
bootstrap.py:257:12: E111 indentation is not a multiple of four
bootstrap.py:455:21: E225 missing whitespace around operator
bootstrap.py:456:62: E226 missing whitespace around arithmetic operator
bootstrap.py:465:9: E265 block comment should start with '# '
bootstrap.py:469:42: E226 missing whitespace around arithmetic operator
bootstrap.py:474:9: E265 block comment should start with '# '
bootstrap.py:481:52: E226 missing whitespace around arithmetic operator
bootstrap.py:494:9: E265 block comment should start with '# '
bootstrap.py:502:9: E265 block comment should start with '# '
bootstrap.py:530:9: E265 block comment should start with '# '
bootstrap.py:537:9: E265 block comment should start with '# '
bootstrap.py:544:9: E265 block comment should start with '# '
bootstrap.py:548:9: E265 block comment should start with '# '
bootstrap.py:552:9: E265 block comment should start with '# '
bootstrap.py:572:9: E265 block comment should start with '# '
bootstrap.py:589:9: E265 block comment should start with '# '
bootstrap.py:589:9: E303 too many blank lines (2)
bootstrap.py:592:9: E265 block comment should start with '# '
bootstrap.py:597:13: E265 block comment should start with '# '
bootstrap.py:598:13: E265 block comment should start with '# '
bootstrap.py:609:13: E265 block comment should start with '# '
bootstrap.py:610:13: E265 block comment should start with '# '
bootstrap.py:611:13: E265 block comment should start with '# '
bootstrap.py:620:13: E265 block comment should start with '# '
bootstrap.py:621:13: E265 block comment should start with '# '
bootstrap.py:630:13: E265 block comment should start with '# '
bootstrap.py:631:13: E265 block comment should start with '# '
bootstrap.py:632:13: E265 block comment should start with '# '
bootstrap.py:644:1: W391 blank line at end of file
```

**Comment by ericzolf** [comment]
On 20/06/16 22:25, Chris Duryee wrote:

> @ericzolf https://github.com/ericzolf Since you are fixing related
> items, can you also fix pep8? A first pass with E501 disabled shows:

Sounds easy enough. Can do.

Eric

**Comment by evgeni** [comment]
@ericzolf ping? :-)

**Comment by ericzolf** [comment]
OK, don't hold your breath, I waited too long and the changes done in the meantime have broken my branch, need to re-base it cleanly...

**Comment by ericzolf** [comment]
OK, the merge was barely possible so I just created another branch and pull request #118 - I'd appreciate if someone with edit rights could include it before it becomes again obsolete.

**Pull request closed without merging**
