### PR TITLE
Added a -f --force option for registration.

### PR DESCRIPTION
**Pull request by my0373**
Added -f option to force registration.

### CODE REVIEW

**Comment by evgeni** [comment]
Hey @my0373, this should be obsolete as of 87ec5a42a180b53d9525170264040f62ad98ffaf, please test :-)

**Comment by my0373** [comment]
Sure, I just need to rebuild my satellite :)

**Comment by mccun934** [comment]
needs a rebase ..

**Comment by evgeni** [comment]
needs a close :)
should be fixed

**Comment by my0373** [comment]
This pull request has been superceeded, closing pull request.

**Pull request closed without merging**
