### PR TITLE
fix rex-urlkeyfile help text (#292)

### PR DESCRIPTION
**Pull request by swadeley**
Improve help text for --rex-urlkeyfile command #292

### CODE REVIEW

**Comment by sideangleside** [comment]
Thanks for the PR @swadeley. LGTM :+1:

**Review by sideangleside — APPROVED** [review]

**Review by evgeni — CHANGES_REQUESTED** [review]
this also needs to be updated in `bootstrap.py`

**Comment by swadeley** [comment]
Hello, sorry for delay. Let me know if I need to squash the commits.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
thanks @swadeley, and no github can squash for us :)

**Comment by swadeley** [comment]
Thank you @evgeni

**Pull request merged**
