### PR TITLE
Nested groups

### PR DESCRIPTION
**Pull request by my0373**
An attempt at adding a -n option to allow nested hostgroups.

### CODE REVIEW

**Comment by evgeni** [comment]
As of 464242fb89fdb4ab07e8fee1355eda06d4c5dbfb this should not be needed anymore.

@my0373 can you verify and close if that is true please? :)

**Comment by mccun934** [comment]
needs a rebase ..

**Comment by evgeni** [comment]
needs a close :)
should be already fixed

**Comment by my0373** [comment]
This pull request has been superceeded, closing pull request.

**Pull request closed without merging**
