### PR TITLE
restart rhsmcertd before migration/registration

### LINKED ISSUE #76: bootstrap hangs if rhsmcertd hangs
situation similar to
https://access.redhat.com/solutions/1342823
https://access.redhat.com/solutions/1754373
https://access.redhat.com/solutions/2110281
https://access.redhat.com/solutions/2202931

should we bounce rhsmcertd before trying?

### PR DESCRIPTION
**Pull request by sideangleside**
Add restart of rhsmcertd service in migration & register functions. closes #76

### CODE REVIEW

**Comment by beav** [comment]
@sideangleside is there a bug logged for RHSM hanging yum installs and requiring a restart?

**Comment by sideangleside** [comment]
@beav in #76 , there are a number of KCS articles listed when either yum or subscription-manager hang and the only resolution is to restart rhsmcertd. I ran into this issue myself, so I'll raise a BZ

**Comment by beav** [comment]
@sideangleside cool, thx :koala: 

the change itself  here looks fine to me. I think just mention the BZ in either a code comment or in the git commit message, so future people know what the root cause is.

**Comment by evgeni** [comment]
FWIW, when I hit that, I had to `pkill` the `rhsmcertd-worker` processes, as a graceful restart of the `rhsmcertd` did not help :/

**Comment by beav** [comment]
ACK

**Comment by beav** [comment]
@sideangleside can you squash this into one commit? It looks like there's a commit for the code change and then another commit on top for the BZ comment that was added.

**Comment by sideangleside** [comment]
with [rhbz1346417](https://bugzilla.redhat.com/show_bug.cgi?id=1346417), subscription-manager now sets a timeout for SSL connections. This PR is no longer needed. (And since it hasn't been merged yet, I'm closing it out)

**Pull request closed without merging**
