### PR TITLE
option to specify the ip of the server

### PR DESCRIPTION
**Pull request by evgeni**
Also gathers the primary IP address if none was given

### CODE REVIEW

**Comment by evgeni** [comment]
This should fix #146

**Review by sideangleside — CHANGES_REQUESTED** [review]
What's a good usage for the --ip switch? Generally when we add a new option, I'd like the README to show the user its usage, especially since it is a non-mandatory option. 

Is it simply useful where the host has multiple interfaces and you wish to control which is used for contacting Foreman? Or are there other usages?

**Comment by evgeni** [comment]
it is only used in the foreman host object, e.g. to contact the machine from foreman (rex). clarified that (at least I hope I did)

**Review by sideangleside — APPROVED** [review]

**Comment by sideangleside** [comment]
I tested on a couple of systems.  Doc text looks good. Merging. :+1:

**Pull request merged**
