### PR TITLE
document required permissions

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@sideangleside @MartijntenHeuvel i can haz review plz?

**Review by sideangleside — CHANGES_REQUESTED** [review]
we'd also need to document the permissions needed when using the --legacy-purge option, which are 

User needs to be an admin of the system in Sat5/RHN by having any of the following roles:

- An organization administrator
- A system group administrator for a system group that the system is a member of. 
- granted permissions to the system explicitly via Users-> account-> 'Systems Administered by this User'

**Comment by MartijntenHeuvel** [comment]
If you give the edit_hosts _role_ this will provide more then required: you can give only create_hosts instead of "view_hosts, create_hosts, edit_hosts, destroy_hosts, build_hosts" which is again more then required. 

you can also create a new role, add only the create_hosts to that; shouldn't that be sufficient?

**Comment by evgeni** [comment]
@sideangleside @MartijntenHeuvel added more words, please re-review.

**Comment by sideangleside** [comment]
:+1:

**Review by sideangleside — APPROVED** [review]

**Comment by MartijntenHeuvel** [comment]
Looks good to me! +1 @evgeni

**Comment by evgeni** [comment]
thanks guys, merging :)

**Pull request merged**
