### PR TITLE
support setting arbitrary servers as Puppet master and CA

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by beav** [comment]
looks good, but can you add `ca_port` as well?

**Comment by evgeni** [comment]
oh dear, you can't specify `ca_server = host:port`? silly

**Comment by beav** [comment]
It might, I didn't try but if it does work it would be an undocumented feature.

https://puppet.com/docs/puppet/5.4/configuration.html#caport

**Comment by evgeni** [comment]
@beav updated and tested :)

**Comment by sideangleside** [comment]
You'd want to add a couple of `print` statements [here](https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L1094) to output the values of the new options when `options.verbose` is true, similar to what we do for the other options. 

Also, update README.md (since you added new options, we have to show the users how to use them ). 

Otherwise, +1 on the changes. No issues on my setup.

**Comment by evgeni** [comment]
@sideangleside I did as you said, not as you did.

**Pull request merged**
